<?php

namespace Database\Seeders;

use Carbon\Carbon;
use DB;
use Illuminate\Database\Seeder;

class ReportGroupSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $accountNames = [
            'ACCIDENT AND EMERGENCY EXPENSES',
            'ACCOUNTS RECEIVABLE',
            'ACCOUNTS RECEIVABLE- NON TRADE',
            'ACCUMULATED DEPRECIATION - BUILDINGS',
            'ACCUMULATED DEPRECIATION - CONSTRUCTION AND HEAVY EQUIPMENT',
            'ACCUMULATED DEPRECIATION - FUEL DEPOT',
            'ACCUMULATED DEPRECIATION - FURNITURES AND FIXTURES',
            'ACCUMULATED DEPRECIATION - INFORMATION AND COMMUNICATION TECHNOLOGY EQUIPMENT',
            'ACCUMULATED DEPRECIATION - TOOLS AND OTHER EQUIPMENT',
            'ADVANCES TO AFFILIATES',
            'ADVANCES TO OFFICERS AND EMPLOYEES',
            'ADVANCES TO SUPPLIERS',
            'AGENCY',
            'AP CLEARING ACCOUNT',
            'ARCHIVE',
            'ASSOCIATION DUES',
            'BANK AND OTHER FINANCIAL CHARGES',
            'BIDDING EXPENSE',
            'BLUEPRINTS AND REPRODUCTION',
            'BOND EXPENSES',
            'BUILDINGS',
            'CASH ADVANCE FOR OPERATING EXPENSE',
            'CASH ADVANCES FOR PAYROLL',
            'CASH IN BANK',
            'CASH IN BANK- BDO',
            'CASH IN BANK- BDO - DOLLAR ACCOUNT',
            'CASH IN BANK- BDO CHECK ACCOUNT',
            'CASH IN BANK- DBP',
            'CASH IN BANK- LANDBANK',
            'CASH IN BANK- LANDBANK-ECDC',
            'CASH IN BANK- LANDBANK-EPCC-ECDC JV',
            'CASH IN BANK- LANDBANK-FG-ECDC JV',
            'CASH IN BANK- LANDBANK-ME3-ECDC JV',
            'CASH IN BANK- LANDBANK-REYROSE-ECDC JV',
            'CASH IN BANK- LANDBANK-UKC-ECDC JV',
            'CASH IN BANK- MAYBANK',
            'CASH IN BANK- ME3/EP JV ACCOUNT',
            'CASH IN BANK- METROBANK',
            'CASH IN BANK- METROBANK - DOLLAR ACCOUNT',
            'CASH IN VAULT',
            'COMMUNICATION EXPENSES',
            'CONSTRUCTION AND HEAVY EQUIPMENT',
            'CONSTRUCTION COST- DEPRECIATION AND AMORTIZATION',
            'CONSTRUCTION COST- EQUIPMENT RENTAL',
            'CONSTRUCTION COST- FUEL',
            'CONSTRUCTION COST- LABOR',
            'CONSTRUCTION COST- MATERIALS',
            'CONSTRUCTION COST- SUBCONTRACTORS',
            'CONSTRUCTION COST- TAXES, LICENSES AND REGISTRATION',
            'CONSTRUCTION EQUIPMENT',
            'CONSTRUCTION IN PROGRESS- ARCHIVE',
            'CONSTRUCTION IN PROGRESS- FUEL DEPOT',
            'CONSTRUCTION IN PROGRESS- FURNITURE & FIXTURES',
            'CONSTRUCTION IN PROGRESS- GUARD HOUSE',
            'CONSTRUCTION IN PROGRESS- HR BUILDING',
            'CONSTRUCTION IN PROGRESS- LIFTER BUILDING',
            'CONSTRUCTION IN PROGRESS- OFFICE BUILDING',
            'CONSTRUCTION IN PROGRESS- PANTRY',
            'CONSTRUCTION IN PROGRESS- PAVING BLOCK',
            'CONSTRUCTION IN PROGRESS- WAREHOUSE',
            'CONSTRUCTION MATERIALS INVENTORY',
            'CONSTRUCTION RELATED EXPENSES',
            'CONSTRUCTION SPARE PARTS INVENTORY',
            'CONTRACT RECEIVABLE',
            'CURRENT LIABILITIES',
            'DOCUMENTARY STAMP TAX',
            'ECDC ACTIVITIES EXPENSE',
            'ELECTRICAL SUPPLIES',
            'ELECTRICITY EXPENSES',
            'EMPLOYEE BENEFITS - 13TH MONTH',
            'EMPLOYEE BENEFITS - HEALTH PLAN',
            'EMPLOYEE BENEFITS- SIL',
            'ENGTECH SOFTWARE',
            'FACILITIES FOR OFFICE AND MOTORPOOL',
            'FACILITIES FOR PROJECT OFFICE & BUNKHOUSE',
            'FEES AND OTHER TAXES',
            'FILING AND PROCESSING FEES',
            'FINANCIAL EXPENSES',
            'FUEL DEPOT',
            'FUEL, OIL AND LUBRICANTS EXPENSES',
            'FUEL, OIL AND LUBRICANTS INVENTORY',
            'FURNITURES AND FIXTURES',
            'HEALTH AND SAFETY',
            'INFORMATION AND COMMUNICATION TECHNOLOGY EQUIPMENT',
            'INPUT VAT',
            'INSURANCE EXPENSE',
            'INTEREST EXPENSE',
            'INTERNET SUBSCRIPTION EXPENSES',
            'INVENTORIES',
            'IT SUPPLIES',
            'LABOR EXPENSE',
            'LAND IMPROVEMENTS',
            'LOAN ACCOMMODATION',
            'MACHINERY',
            'MARKETING EXPENSE',
            'MATERIALS',
            'MEALS EXPENSE',
            'MISCELLANEOUS EXPENSE',
            'MOBILE AND TELEPHONE EXPENSES',
            'MOTORCYCLE',
            'NONCURRENT LIABILITIES',
            'NOTARIAL SERVICES',
            'OFFICE EQUIPMENT',
            'OFFICE SUPPLIES',
            'OFFICE SUPPLIES INVENTORY',
            'OTHER BENEFITS- ALLOWANCE',
            'OTHER CURRENT LIABILITIES',
            'OTHER FACILITIES EXPENSE: ICT AND OFFICE EQUIPMENT',
            'OTHER FACILITIES EXPENSE: TOOL AND OTHER EQUIPMENT',
            'OTHER FEES',
            'OTHER INVENTORY',
            'OTHER PREPAID EXPENSES',
            'OTHER RECEIVABLES',
            'OTHER SUPPLIES',
            'OVERTIME PAY',
            'PANTRY AND HOUSEKEEPING SUPPLIES',
            'PANTRY AND HOUSEKEEPING SUPPLIES INVENTORY',
            "PARTNER'S EQUITY",
            'PENALTIES, SURCHARGES, LITIGATION AND SETTLEMENT FEES',
            'PERSONNEL DEVELOPMENT AND TRAINING EXPENSES',
            'PETTY CASH FUND: EQUIPMENT MANAGEMENT SECTION',
            'PETTY CASH FUND: MARKETING SECTION',
            'PHIC PREMIUMS',
            'POSTAGE AND COURIER SERVICES',
            'PREPAID ASSET',
            'PREPAID MEMBERSHIP DUES',
            'PREPAID RENT',
            'PREPAID SOFTWARE',
            'PROFESSIONAL SERVICES',
            'PROPERTY, PLANT AND EQUIPMENT',
            'RECEIVABLE - RROW',
            'RECEIVABLE: RELATED PARTIES',
            'RECEIVABLE: SECURITY DEPOSIT',
            'RECEIVABLE: SSS REIMBURSEMENT',
            'RECRUITMENT EXPENSE',
            'RENT EXPENSE',
            'REPAIRS AND MAINTENANCE',
            'REPLENISHMENT',
            'REPRESENTATION EXPENSE',
            'REPRESENTATION EXPENSE- BIR',
            'RETENTION RECEIVABLE',
            'REVENUE',
            'REVOLVING FUND',
            'ROYALTY EXPENSE',
            'SALARIES AND WAGES - BASIC PAY',
            'SALARIES AND WAGES - DIFFERENTIAL',
            'SECURITY SERVICES',
            'SERVICE VEHICLES',
            'SHIPMENT, FREIGHT AND HANDLING EXPENSES',
            'SOLICITATION AND DONATION',
            'SSS PREMIUMS',
            'SUBSCRIPTIONS EXPENSE',
            'TOLL AND PERENNIAL',
            'TOOLS AND OTHER EQUIPMENT',
            'TRAVELING EXPENSES',
            'TUBIG',
            'UNIFORM EXPENSE',
            'UTILITIES EXPENSE: LIGHT AND WATER',
            'VEHICLE PERMITS & LICENSES',
            'VEHICLES',
            'WATER EXPENSES',
            'DEPRECIATION AND AMORTIZATION',
            'HDMF PREMIUMS',
            'PROPERTY PLANT AND EQUIPMENT',
        ];

        $now = Carbon::now();
        $data = array_map(function ($name, $index) use ($now) {
            return [
                'id' => $index + 1,
                'name' => $name,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }, $accountNames, array_keys($accountNames));

        DB::table('report_groups')->upsert($data, ['name']);
    }
}
