<?php

namespace App\Enums\Terms;

enum HrmsTerms: string
{
    case SALARY_AND_WAGES_BASIC_PAY = 'SALARY_AND_WAGES_BASIC_PAY';
    case SALARY_AND_WAGES_BASIC_PAY_OFFICE = 'SALARY_AND_WAGES_BASIC_PAY_OFFICE';
    case SALARY_AND_WAGES_OT_PAY = 'SALARY_AND_WAGES_OT_PAY';
    case SALARY_AND_WAGES_OT_PAY_OFFICE = 'SALARY_AND_WAGES_OT_PAY_OFFICE';
    case SALARY_AND_WAGES_HOLIDAY_PAY = 'SALARY_AND_WAGES_HOLIDAY_PAY';
    case SALARY_AND_WAGES_HOLIDAY_PAY_OFFICE = 'SALARY_AND_WAGES_HOLIDAY_PAY_OFFICE';
    case OVERTIME_PAY = 'OVERTIME_PAY';
    case CASH_IN_BANK_MAYBANK = 'CASH_IN_BANK_MAYBANK';
    case SSS_PREMIUM_PAYABLE = 'SSS_PREMIUM_PAYABLE';
    case SSS_PREMIUM_PAYABLE_OFFICE = 'SSS_PREMIUM_PAYABLE_OFFICE';
    case SSS_SALARY_CALAMITY_LOAN_PAY = 'SSS_SALARY_CALAMITY_LOAN_PAY';
    case HDMF_PREMIUM_PAYABLE = 'HDMF_PREMIUM_PAYABLE';
    case HDMF_PREMIUM_PAYABLE_OFFICE = 'HDMF_PREMIUM_PAYABLE_OFFICE';
    case HDMF_SALARY_CALAMITY_LOAN_PAY = 'HDMF_SALARY_CALAMITY_LOAN_PAY';
    case HDMF_MODIFIED_PAG_IBIG_2 = 'HDMF_MODIFIED_PAG_IBIG_2';
    case PHIC_PREMIUM_PAYABLE = 'PHIC_PREMIUM_PAYABLE';
    case PHIC_PREMIUM_PAYABLE_OFFICE = 'PHIC_PREMIUM_PAYABLE_OFFICE';
    public static function values(): array
    {
        return array_column(self::cases(), 'value');
    }
}
