openapi: 3.0.0
info:
  title: API Documentation
  description: API endpoints for the application
  version: 1.0.0

paths:
  /api/sync/all:
    post:
      summary: Sync all projects
      description: Sync all projects using the user's token
      security:
        - bearerAuth: []
      responses:
        200:
          description: Sync successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        500:
          description: Sync failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string

  /api/sync/project:
    post:
      summary: Sync a single project
      description: Sync a single project using the user's token
      security:
        - bearerAuth: []
      responses:
        200:
          description: Sync successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        500:
          description: Sync failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string

  /api/approvals/approve/{modelName}/{model}:
    post:
      summary: Approve an approval request
      description: Approve an approval request for the specified model and model ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: modelName
          required: true
          schema:
            type: string
        - in: path
          name: model
          required: true
          schema:
            type: string
      responses:
        200:
          description: Approval successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        500:
          description: Approval failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string

  /api/approvals/disapprove/{modelName}/{model}:
    post:
      summary: Disapprove an approval request
      description: Disapprove an approval request for the specified model and model ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: modelName
          required: true
          schema:
            type: string
        - in: path
          name: model
          required: true
          schema:
            type: string
      responses:
        200:
          description: Disapproval successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        500:
          description: Disapproval failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string

  /api/approvals/void/{modelName}/{model}:
    post:
      summary: Void an approval request
      description: Void an approval request for the specified model and model ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: modelName
          required: true
          schema:
            type: string
        - in: path
          name: model
          required: true
          schema:
            type: string
      responses:
        200:
          description: Void successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        500:
          description: Void failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string

  /api/voucher/status:
    get:
      summary: Get voucher status
      description: Get the available voucher status
      security:
        - bearerAuth: []
      responses:
        200:
          description: Voucher status retrieved successfully
          content:
            application/json
