<?php

namespace App\Enums\Reports;

enum OfficeExpense: int
{
    case SALARIES_AND_WAGES_BASIC_PAY = 'SALARIES AND WAGES BASIC PAY';
    case OVERTIME_PAY = 'OVERTIME PAY';
    case EMPLOYEE_BENEFITS_13TH_MONTH = 'EMPLOYEE BENEFITS - 13TH MONTH';
    case EMPLOYEE_BENEFITS_HEALTH_PLAN = 'EMPLOYEE BENEFITS - HEALTH PLAN';
    case EMPLOYEE_BENEFITS_ALLOWANCE = 'EMPLOYEE BENEFITS - ALLOWANCE';
    case PAGIBIG_PREMIUM = 'HDMF PREMIUMS';
    case PHILHEALTH_PREMIUM = 'PHIC PREMIUMS';
    case GSIS_PREMIUM = 'GSIS PREMIUMS';
    case SSS_PREMIUM = 'SSS PREMIUMS';
}
